services:
  - type: web
    name: allfilechanger-imgtopdf-api
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "4"
    healthCheckPath: /health
    autoDeploy: true
